#!/usr/bin/env ruby

$:.unshift(File.join File.expand_path(File.dirname(__FILE__)), 'lib', 'rsulley')

require 'rsulley'
include RSulley

script = ARGV[0].dup
script += '.rb' unless script =~ /\.rb$/i
load script
